version: 0.0
os: linux
files:
    - source: /
        destination: /var/www/laravel-portfolio

permissions:
    - object: /var/www/laravel-portfolio
        owner: koki
        group: koki

hooks:
    AfterInstall:
        - location: ./scripts/after_install.sh
            timeout: 60
            runas: koki
